2 курс
======

На втором курсе у меня был предмет "Структуры и алгоритмы данных", который вёл Андрианов Игорь Александрович.
Там я решил сделать курсовой проект, связанный с распознаванием изображений. Назвал работу "**Распознавание рукописных цифр полным перебором через метод свёртки с отсечениями**". К сожалению, построение нейронной сети на C++ не осилил, но написал хитрый и быстрый "брутфорсер" (о котором как-то писал в блоге: http://blog.lalf.ru/2011/06/blog-post.html ).
Ошибки при распознавании были, и очень даже значимые, но зато я познакомился с замечательной библиотекой FreeImage =)

**Оценка**: 4

Скриншоты
---------

.. image:: https://raw.github.com/saippuakauppias/my_university_files/master/2_year/structures_and_algorithms/screenshot1.png

.. image:: https://raw.github.com/saippuakauppias/my_university_files/master/2_year/structures_and_algorithms/screenshot2.png
