#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Data.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace dekan {
    using namespace System;
    ref class DataSet3;
    
    
    /// <summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0"), 
    System::Serializable, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::ComponentModel::ToolboxItem(true), 
    System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedDataSetSchema"), 
    System::Xml::Serialization::XmlRootAttribute(L"DataSet3"), 
    System::ComponentModel::Design::HelpKeywordAttribute(L"vs.data.DataSet")]
    public ref class DataSet3 : public ::System::Data::DataSet {
        public : ref class GROUPSDataTable;
        public : ref class VIEW_MARKS_GROUPDataTable;
        public : ref class GROUPSRow;
        public : ref class VIEW_MARKS_GROUPRow;
        public : ref class GROUPSRowChangeEvent;
        public : ref class VIEW_MARKS_GROUPRowChangeEvent;
        
        private: dekan::DataSet3::GROUPSDataTable^  tableGROUPS;
        
        private: dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  tableVIEW_MARKS_GROUP;
        
        private: ::System::Data::SchemaSerializationMode _schemaSerializationMode;
        
        public : delegate System::Void GROUPSRowChangeEventHandler(::System::Object^  sender, dekan::DataSet3::GROUPSRowChangeEvent^  e);
        
        public : delegate System::Void VIEW_MARKS_GROUPRowChangeEventHandler(::System::Object^  sender, dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEvent^  e);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        DataSet3();
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        DataSet3(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::Browsable(false), 
        System::ComponentModel::DesignerSerializationVisibility(::System::ComponentModel::DesignerSerializationVisibility::Content)]
        property dekan::DataSet3::GROUPSDataTable^  GROUPS {
            dekan::DataSet3::GROUPSDataTable^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::Browsable(false), 
        System::ComponentModel::DesignerSerializationVisibility(::System::ComponentModel::DesignerSerializationVisibility::Content)]
        property dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  VIEW_MARKS_GROUP {
            dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::BrowsableAttribute(true), 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Visible)]
        virtual property ::System::Data::SchemaSerializationMode SchemaSerializationMode {
            ::System::Data::SchemaSerializationMode get() override;
            System::Void set(::System::Data::SchemaSerializationMode value) override;
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Hidden)]
        property ::System::Data::DataTableCollection^  Tables {
            ::System::Data::DataTableCollection^  get() new;
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Hidden)]
        property ::System::Data::DataRelationCollection^  Relations {
            ::System::Data::DataRelationCollection^  get() new;
        }
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Void InitializeDerivedDataSet() override;
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Data::DataSet^  Clone() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Boolean ShouldSerializeTables() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Boolean ShouldSerializeRelations() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Void ReadXmlSerializable(::System::Xml::XmlReader^  reader) override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Xml::Schema::XmlSchema^  GetSchemaSerializable() override;
        
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Void InitVars();
        
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Void InitVars(::System::Boolean initTable);
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Void InitClass();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Boolean ShouldSerializeGROUPS();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Boolean ShouldSerializeVIEW_MARKS_GROUP();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Void SchemaChanged(::System::Object^  sender, ::System::ComponentModel::CollectionChangeEventArgs^  e);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedDataSetSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
        
        public : /// <summary>
///Represents the strongly named DataTable class.
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0"), 
        System::Serializable, 
        System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedTableSchema")]
        ref class GROUPSDataTable : public ::System::Data::DataTable, public ::System::Collections::IEnumerable {
            
            private: ::System::Data::DataColumn^  columnID_GROUP;
            
            private: ::System::Data::DataColumn^  columnGROUPNAME;
            
            public: event dekan::DataSet3::GROUPSRowChangeEventHandler^  GROUPSRowChanging;
            
            public: event dekan::DataSet3::GROUPSRowChangeEventHandler^  GROUPSRowChanged;
            
            public: event dekan::DataSet3::GROUPSRowChangeEventHandler^  GROUPSRowDeleting;
            
            public: event dekan::DataSet3::GROUPSRowChangeEventHandler^  GROUPSRowDeleted;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSDataTable();
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSDataTable(::System::Data::DataTable^  table);
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  ID_GROUPColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  GROUPNAMEColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::ComponentModel::Browsable(false)]
            property ::System::Int32 Count {
                ::System::Int32 get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property dekan::DataSet3::GROUPSRow^  default [::System::Int32 ] {
                dekan::DataSet3::GROUPSRow^  get(::System::Int32 index);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void AddGROUPSRow(dekan::DataSet3::GROUPSRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet3::GROUPSRow^  AddGROUPSRow(System::Decimal ID_GROUP, System::String^  GROUPNAME);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet3::GROUPSRow^  FindByID_GROUP(System::Decimal ID_GROUP);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Collections::IEnumerator^  GetEnumerator();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataTable^  Clone() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataTable^  CreateInstance() override;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void InitVars();
            
            private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void InitClass();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet3::GROUPSRow^  NewGROUPSRow();
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataRow^  NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Type^  GetRowType() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) override;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void RemoveGROUPSRow(dekan::DataSet3::GROUPSRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
        };
        
        public : /// <summary>
///Represents the strongly named DataTable class.
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0"), 
        System::Serializable, 
        System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedTableSchema")]
        ref class VIEW_MARKS_GROUPDataTable : public ::System::Data::DataTable, public ::System::Collections::IEnumerable {
            
            private: ::System::Data::DataColumn^  columnCOURSE;
            
            private: ::System::Data::DataColumn^  columnFULLNAME;
            
            private: ::System::Data::DataColumn^  columnVALUE_MARK;
            
            private: ::System::Data::DataColumn^  columnDATE_MARK;
            
            private: ::System::Data::DataColumn^  columnDISCNAME;
            
            private: ::System::Data::DataColumn^  columnGROUPNAME;
            
            public: event dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEventHandler^  VIEW_MARKS_GROUPRowChanging;
            
            public: event dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEventHandler^  VIEW_MARKS_GROUPRowChanged;
            
            public: event dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEventHandler^  VIEW_MARKS_GROUPRowDeleting;
            
            public: event dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEventHandler^  VIEW_MARKS_GROUPRowDeleted;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            VIEW_MARKS_GROUPDataTable();
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            VIEW_MARKS_GROUPDataTable(::System::Data::DataTable^  table);
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            VIEW_MARKS_GROUPDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  COURSEColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  FULLNAMEColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  VALUE_MARKColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  DATE_MARKColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  DISCNAMEColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  GROUPNAMEColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::ComponentModel::Browsable(false)]
            property ::System::Int32 Count {
                ::System::Int32 get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property dekan::DataSet3::VIEW_MARKS_GROUPRow^  default [::System::Int32 ] {
                dekan::DataSet3::VIEW_MARKS_GROUPRow^  get(::System::Int32 index);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void AddVIEW_MARKS_GROUPRow(dekan::DataSet3::VIEW_MARKS_GROUPRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet3::VIEW_MARKS_GROUPRow^  AddVIEW_MARKS_GROUPRow(
                        System::Decimal COURSE, 
                        System::String^  FULLNAME, 
                        System::Decimal VALUE_MARK, 
                        System::DateTime DATE_MARK, 
                        System::String^  DISCNAME, 
                        System::String^  GROUPNAME);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Collections::IEnumerator^  GetEnumerator();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataTable^  Clone() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataTable^  CreateInstance() override;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void InitVars();
            
            private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void InitClass();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet3::VIEW_MARKS_GROUPRow^  NewVIEW_MARKS_GROUPRow();
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataRow^  NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Type^  GetRowType() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) override;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void RemoveVIEW_MARKS_GROUPRow(dekan::DataSet3::VIEW_MARKS_GROUPRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
        };
        
        public : /// <summary>
///Represents strongly named DataRow class.
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0")]
        ref class GROUPSRow : public ::System::Data::DataRow {
            
            private: dekan::DataSet3::GROUPSDataTable^  tableGROUPS;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSRow(::System::Data::DataRowBuilder^  rb);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::Decimal ID_GROUP {
                System::Decimal get();
                System::Void set(System::Decimal value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::String^  GROUPNAME {
                System::String^  get();
                System::Void set(System::String^  value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsGROUPNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetGROUPNAMENull();
        };
        
        public : /// <summary>
///Represents strongly named DataRow class.
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0")]
        ref class VIEW_MARKS_GROUPRow : public ::System::Data::DataRow {
            
            private: dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  tableVIEW_MARKS_GROUP;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            VIEW_MARKS_GROUPRow(::System::Data::DataRowBuilder^  rb);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::Decimal COURSE {
                System::Decimal get();
                System::Void set(System::Decimal value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::String^  FULLNAME {
                System::String^  get();
                System::Void set(System::String^  value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::Decimal VALUE_MARK {
                System::Decimal get();
                System::Void set(System::Decimal value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::DateTime DATE_MARK {
                System::DateTime get();
                System::Void set(System::DateTime value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::String^  DISCNAME {
                System::String^  get();
                System::Void set(System::String^  value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::String^  GROUPNAME {
                System::String^  get();
                System::Void set(System::String^  value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsCOURSENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetCOURSENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsFULLNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetFULLNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsVALUE_MARKNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetVALUE_MARKNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsDATE_MARKNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetDATE_MARKNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsDISCNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetDISCNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsGROUPNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetGROUPNAMENull();
        };
        
        public : /// <summary>
///Row event argument class
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0")]
        ref class GROUPSRowChangeEvent : public ::System::EventArgs {
            
            private: dekan::DataSet3::GROUPSRow^  eventRow;
            
            private: ::System::Data::DataRowAction eventAction;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSRowChangeEvent(dekan::DataSet3::GROUPSRow^  row, ::System::Data::DataRowAction action);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property dekan::DataSet3::GROUPSRow^  Row {
                dekan::DataSet3::GROUPSRow^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataRowAction Action {
                ::System::Data::DataRowAction get();
            }
        };
        
        public : /// <summary>
///Row event argument class
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0")]
        ref class VIEW_MARKS_GROUPRowChangeEvent : public ::System::EventArgs {
            
            private: dekan::DataSet3::VIEW_MARKS_GROUPRow^  eventRow;
            
            private: ::System::Data::DataRowAction eventAction;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            VIEW_MARKS_GROUPRowChangeEvent(dekan::DataSet3::VIEW_MARKS_GROUPRow^  row, ::System::Data::DataRowAction action);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property dekan::DataSet3::VIEW_MARKS_GROUPRow^  Row {
                dekan::DataSet3::VIEW_MARKS_GROUPRow^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataRowAction Action {
                ::System::Data::DataRowAction get();
            }
        };
    };
}
namespace dekan {
    
    
    inline DataSet3::DataSet3() {
        this->BeginInit();
        this->InitClass();
        ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &dekan::DataSet3::SchemaChanged);
        __super::Tables->CollectionChanged += schemaChangedHandler;
        __super::Relations->CollectionChanged += schemaChangedHandler;
        this->EndInit();
    }
    
    inline DataSet3::DataSet3(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context) : 
            ::System::Data::DataSet(info, context, false) {
        if (this->IsBinarySerialized(info, context) == true) {
            this->InitVars(false);
            ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler1 = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &dekan::DataSet3::SchemaChanged);
            this->Tables->CollectionChanged += schemaChangedHandler1;
            this->Relations->CollectionChanged += schemaChangedHandler1;
            return;
        }
        ::System::String^  strSchema = (cli::safe_cast<::System::String^  >(info->GetValue(L"XmlSchema", ::System::String::typeid)));
        if (this->DetermineSchemaSerializationMode(info, context) == ::System::Data::SchemaSerializationMode::IncludeSchema) {
            ::System::Data::DataSet^  ds = (gcnew ::System::Data::DataSet());
            ds->ReadXmlSchema((gcnew ::System::Xml::XmlTextReader((gcnew ::System::IO::StringReader(strSchema)))));
            if (ds->Tables[L"GROUPS"] != nullptr) {
                __super::Tables->Add((gcnew dekan::DataSet3::GROUPSDataTable(ds->Tables[L"GROUPS"])));
            }
            if (ds->Tables[L"VIEW_MARKS_GROUP"] != nullptr) {
                __super::Tables->Add((gcnew dekan::DataSet3::VIEW_MARKS_GROUPDataTable(ds->Tables[L"VIEW_MARKS_GROUP"])));
            }
            this->DataSetName = ds->DataSetName;
            this->Prefix = ds->Prefix;
            this->Namespace = ds->Namespace;
            this->Locale = ds->Locale;
            this->CaseSensitive = ds->CaseSensitive;
            this->EnforceConstraints = ds->EnforceConstraints;
            this->Merge(ds, false, ::System::Data::MissingSchemaAction::Add);
            this->InitVars();
        }
        else {
            this->ReadXmlSchema((gcnew ::System::Xml::XmlTextReader((gcnew ::System::IO::StringReader(strSchema)))));
        }
        this->GetSerializationData(info, context);
        ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &dekan::DataSet3::SchemaChanged);
        __super::Tables->CollectionChanged += schemaChangedHandler;
        this->Relations->CollectionChanged += schemaChangedHandler;
    }
    
    inline dekan::DataSet3::GROUPSDataTable^  DataSet3::GROUPS::get() {
        return this->tableGROUPS;
    }
    
    inline dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  DataSet3::VIEW_MARKS_GROUP::get() {
        return this->tableVIEW_MARKS_GROUP;
    }
    
    inline ::System::Data::SchemaSerializationMode DataSet3::SchemaSerializationMode::get() {
        return this->_schemaSerializationMode;
    }
    inline System::Void DataSet3::SchemaSerializationMode::set(::System::Data::SchemaSerializationMode value) {
        this->_schemaSerializationMode = __identifier(value);
    }
    
    inline ::System::Data::DataTableCollection^  DataSet3::Tables::get() {
        return __super::Tables;
    }
    
    inline ::System::Data::DataRelationCollection^  DataSet3::Relations::get() {
        return __super::Relations;
    }
    
    inline ::System::Void DataSet3::InitializeDerivedDataSet() {
        this->BeginInit();
        this->InitClass();
        this->EndInit();
    }
    
    inline ::System::Data::DataSet^  DataSet3::Clone() {
        dekan::DataSet3^  cln = (cli::safe_cast<dekan::DataSet3^  >(__super::Clone()));
        cln->InitVars();
        cln->SchemaSerializationMode = this->SchemaSerializationMode;
        return cln;
    }
    
    inline ::System::Boolean DataSet3::ShouldSerializeTables() {
        return false;
    }
    
    inline ::System::Boolean DataSet3::ShouldSerializeRelations() {
        return false;
    }
    
    inline ::System::Void DataSet3::ReadXmlSerializable(::System::Xml::XmlReader^  reader) {
        if (this->DetermineSchemaSerializationMode(reader) == ::System::Data::SchemaSerializationMode::IncludeSchema) {
            this->Reset();
            ::System::Data::DataSet^  ds = (gcnew ::System::Data::DataSet());
            ds->ReadXml(reader);
            if (ds->Tables[L"GROUPS"] != nullptr) {
                __super::Tables->Add((gcnew dekan::DataSet3::GROUPSDataTable(ds->Tables[L"GROUPS"])));
            }
            if (ds->Tables[L"VIEW_MARKS_GROUP"] != nullptr) {
                __super::Tables->Add((gcnew dekan::DataSet3::VIEW_MARKS_GROUPDataTable(ds->Tables[L"VIEW_MARKS_GROUP"])));
            }
            this->DataSetName = ds->DataSetName;
            this->Prefix = ds->Prefix;
            this->Namespace = ds->Namespace;
            this->Locale = ds->Locale;
            this->CaseSensitive = ds->CaseSensitive;
            this->EnforceConstraints = ds->EnforceConstraints;
            this->Merge(ds, false, ::System::Data::MissingSchemaAction::Add);
            this->InitVars();
        }
        else {
            this->ReadXml(reader);
            this->InitVars();
        }
    }
    
    inline ::System::Xml::Schema::XmlSchema^  DataSet3::GetSchemaSerializable() {
        ::System::IO::MemoryStream^  stream = (gcnew ::System::IO::MemoryStream());
        this->WriteXmlSchema((gcnew ::System::Xml::XmlTextWriter(stream, nullptr)));
        stream->Position = 0;
        return ::System::Xml::Schema::XmlSchema::Read((gcnew ::System::Xml::XmlTextReader(stream)), nullptr);
    }
    
    inline ::System::Void DataSet3::InitVars() {
        this->InitVars(true);
    }
    
    inline ::System::Void DataSet3::InitVars(::System::Boolean initTable) {
        this->tableGROUPS = (cli::safe_cast<dekan::DataSet3::GROUPSDataTable^  >(__super::Tables[L"GROUPS"]));
        if (initTable == true) {
            if (this->tableGROUPS != nullptr) {
                this->tableGROUPS->InitVars();
            }
        }
        this->tableVIEW_MARKS_GROUP = (cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  >(__super::Tables[L"VIEW_MARKS_GROUP"]));
        if (initTable == true) {
            if (this->tableVIEW_MARKS_GROUP != nullptr) {
                this->tableVIEW_MARKS_GROUP->InitVars();
            }
        }
    }
    
    inline ::System::Void DataSet3::InitClass() {
        this->DataSetName = L"DataSet3";
        this->Prefix = L"";
        this->Namespace = L"http://tempuri.org/DataSet3.xsd";
        this->EnforceConstraints = true;
        this->SchemaSerializationMode = ::System::Data::SchemaSerializationMode::IncludeSchema;
        this->tableGROUPS = (gcnew dekan::DataSet3::GROUPSDataTable());
        __super::Tables->Add(this->tableGROUPS);
        this->tableVIEW_MARKS_GROUP = (gcnew dekan::DataSet3::VIEW_MARKS_GROUPDataTable());
        __super::Tables->Add(this->tableVIEW_MARKS_GROUP);
    }
    
    inline ::System::Boolean DataSet3::ShouldSerializeGROUPS() {
        return false;
    }
    
    inline ::System::Boolean DataSet3::ShouldSerializeVIEW_MARKS_GROUP() {
        return false;
    }
    
    inline ::System::Void DataSet3::SchemaChanged(::System::Object^  sender, ::System::ComponentModel::CollectionChangeEventArgs^  e) {
        if (e->Action == ::System::ComponentModel::CollectionChangeAction::Remove) {
            this->InitVars();
        }
    }
    
    inline ::System::Xml::Schema::XmlSchemaComplexType^  DataSet3::GetTypedDataSetSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
        dekan::DataSet3^  ds = (gcnew dekan::DataSet3());
        ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
        ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
        ::System::Xml::Schema::XmlSchemaAny^  any = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any->Namespace = ds->Namespace;
        sequence->Items->Add(any);
        type->Particle = sequence;
        ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
        if (xs->Contains(dsSchema->TargetNamespace)) {
            ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
            ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
            try {
                ::System::Xml::Schema::XmlSchema^  schema = nullptr;
                dsSchema->Write(s1);
                for (                ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();                 ) {
                    schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                    s2->SetLength(0);
                    schema->Write(s2);
                    if (s1->Length == s2->Length) {
                        s1->Position = 0;
                        s2->Position = 0;
                        for (                        ; ((s1->Position != s1->Length) 
                                    && (s1->ReadByte() == s2->ReadByte()));                         ) {
                            ;
                        }
                        if (s1->Position == s1->Length) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if (s1 != nullptr) {
                    s1->Close();
                }
                if (s2 != nullptr) {
                    s2->Close();
                }
            }
        }
        xs->Add(dsSchema);
        return type;
    }
    
    
    inline DataSet3::GROUPSDataTable::GROUPSDataTable() {
        this->TableName = L"GROUPS";
        this->BeginInit();
        this->InitClass();
        this->EndInit();
    }
    
    inline DataSet3::GROUPSDataTable::GROUPSDataTable(::System::Data::DataTable^  table) {
        this->TableName = table->TableName;
        if (table->CaseSensitive != table->DataSet->CaseSensitive) {
            this->CaseSensitive = table->CaseSensitive;
        }
        if (table->Locale->ToString() != table->DataSet->Locale->ToString()) {
            this->Locale = table->Locale;
        }
        if (table->Namespace != table->DataSet->Namespace) {
            this->Namespace = table->Namespace;
        }
        this->Prefix = table->Prefix;
        this->MinimumCapacity = table->MinimumCapacity;
    }
    
    inline DataSet3::GROUPSDataTable::GROUPSDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context) : 
            ::System::Data::DataTable(info, context) {
        this->InitVars();
    }
    
    inline ::System::Data::DataColumn^  DataSet3::GROUPSDataTable::ID_GROUPColumn::get() {
        return this->columnID_GROUP;
    }
    
    inline ::System::Data::DataColumn^  DataSet3::GROUPSDataTable::GROUPNAMEColumn::get() {
        return this->columnGROUPNAME;
    }
    
    inline ::System::Int32 DataSet3::GROUPSDataTable::Count::get() {
        return this->Rows->Count;
    }
    
    inline dekan::DataSet3::GROUPSRow^  DataSet3::GROUPSDataTable::default::get(::System::Int32 index) {
        return (cli::safe_cast<dekan::DataSet3::GROUPSRow^  >(this->Rows[index]));
    }
    
    inline ::System::Void DataSet3::GROUPSDataTable::AddGROUPSRow(dekan::DataSet3::GROUPSRow^  row) {
        this->Rows->Add(row);
    }
    
    inline dekan::DataSet3::GROUPSRow^  DataSet3::GROUPSDataTable::AddGROUPSRow(System::Decimal ID_GROUP, System::String^  GROUPNAME) {
        dekan::DataSet3::GROUPSRow^  rowGROUPSRow = (cli::safe_cast<dekan::DataSet3::GROUPSRow^  >(this->NewRow()));
        cli::array< ::System::Object^  >^  columnValuesArray = gcnew cli::array< ::System::Object^  >(2) {ID_GROUP, GROUPNAME};
        rowGROUPSRow->ItemArray = columnValuesArray;
        this->Rows->Add(rowGROUPSRow);
        return rowGROUPSRow;
    }
    
    inline dekan::DataSet3::GROUPSRow^  DataSet3::GROUPSDataTable::FindByID_GROUP(System::Decimal ID_GROUP) {
        return (cli::safe_cast<dekan::DataSet3::GROUPSRow^  >(this->Rows->Find(gcnew cli::array< System::Object^  >(1) {ID_GROUP})));
    }
    
    inline ::System::Collections::IEnumerator^  DataSet3::GROUPSDataTable::GetEnumerator() {
        return this->Rows->GetEnumerator();
    }
    
    inline ::System::Data::DataTable^  DataSet3::GROUPSDataTable::Clone() {
        dekan::DataSet3::GROUPSDataTable^  cln = (cli::safe_cast<dekan::DataSet3::GROUPSDataTable^  >(__super::Clone()));
        cln->InitVars();
        return cln;
    }
    
    inline ::System::Data::DataTable^  DataSet3::GROUPSDataTable::CreateInstance() {
        return (gcnew dekan::DataSet3::GROUPSDataTable());
    }
    
    inline ::System::Void DataSet3::GROUPSDataTable::InitVars() {
        this->columnID_GROUP = __super::Columns[L"ID_GROUP"];
        this->columnGROUPNAME = __super::Columns[L"GROUPNAME"];
    }
    
    inline ::System::Void DataSet3::GROUPSDataTable::InitClass() {
        this->columnID_GROUP = (gcnew ::System::Data::DataColumn(L"ID_GROUP", ::System::Decimal::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnID_GROUP);
        this->columnGROUPNAME = (gcnew ::System::Data::DataColumn(L"GROUPNAME", ::System::String::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnGROUPNAME);
        this->Constraints->Add((gcnew ::System::Data::UniqueConstraint(L"Constraint1", gcnew cli::array< ::System::Data::DataColumn^  >(1) {this->columnID_GROUP}, 
                true)));
        this->columnID_GROUP->AllowDBNull = false;
        this->columnID_GROUP->Unique = true;
        this->columnGROUPNAME->MaxLength = 4000;
    }
    
    inline dekan::DataSet3::GROUPSRow^  DataSet3::GROUPSDataTable::NewGROUPSRow() {
        return (cli::safe_cast<dekan::DataSet3::GROUPSRow^  >(this->NewRow()));
    }
    
    inline ::System::Data::DataRow^  DataSet3::GROUPSDataTable::NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) {
        return (gcnew dekan::DataSet3::GROUPSRow(builder));
    }
    
    inline ::System::Type^  DataSet3::GROUPSDataTable::GetRowType() {
        return dekan::DataSet3::GROUPSRow::typeid;
    }
    
    inline ::System::Void DataSet3::GROUPSDataTable::OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanged(e);
        {
            this->GROUPSRowChanged(this, (gcnew dekan::DataSet3::GROUPSRowChangeEvent((cli::safe_cast<dekan::DataSet3::GROUPSRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet3::GROUPSDataTable::OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanging(e);
        {
            this->GROUPSRowChanging(this, (gcnew dekan::DataSet3::GROUPSRowChangeEvent((cli::safe_cast<dekan::DataSet3::GROUPSRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet3::GROUPSDataTable::OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleted(e);
        {
            this->GROUPSRowDeleted(this, (gcnew dekan::DataSet3::GROUPSRowChangeEvent((cli::safe_cast<dekan::DataSet3::GROUPSRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet3::GROUPSDataTable::OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleting(e);
        {
            this->GROUPSRowDeleting(this, (gcnew dekan::DataSet3::GROUPSRowChangeEvent((cli::safe_cast<dekan::DataSet3::GROUPSRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet3::GROUPSDataTable::RemoveGROUPSRow(dekan::DataSet3::GROUPSRow^  row) {
        this->Rows->Remove(row);
    }
    
    inline ::System::Xml::Schema::XmlSchemaComplexType^  DataSet3::GROUPSDataTable::GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
        ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
        ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
        dekan::DataSet3^  ds = (gcnew dekan::DataSet3());
        ::System::Xml::Schema::XmlSchemaAny^  any1 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any1->Namespace = L"http://www.w3.org/2001/XMLSchema";
        any1->MinOccurs = ::System::Decimal(0);
        any1->MaxOccurs = ::System::Decimal::MaxValue;
        any1->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any1);
        ::System::Xml::Schema::XmlSchemaAny^  any2 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any2->Namespace = L"urn:schemas-microsoft-com:xml-diffgram-v1";
        any2->MinOccurs = ::System::Decimal(1);
        any2->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any2);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute1 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute1->Name = L"namespace";
        attribute1->FixedValue = ds->Namespace;
        type->Attributes->Add(attribute1);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute2 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute2->Name = L"tableTypeName";
        attribute2->FixedValue = L"GROUPSDataTable";
        type->Attributes->Add(attribute2);
        type->Particle = sequence;
        ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
        if (xs->Contains(dsSchema->TargetNamespace)) {
            ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
            ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
            try {
                ::System::Xml::Schema::XmlSchema^  schema = nullptr;
                dsSchema->Write(s1);
                for (                ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();                 ) {
                    schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                    s2->SetLength(0);
                    schema->Write(s2);
                    if (s1->Length == s2->Length) {
                        s1->Position = 0;
                        s2->Position = 0;
                        for (                        ; ((s1->Position != s1->Length) 
                                    && (s1->ReadByte() == s2->ReadByte()));                         ) {
                            ;
                        }
                        if (s1->Position == s1->Length) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if (s1 != nullptr) {
                    s1->Close();
                }
                if (s2 != nullptr) {
                    s2->Close();
                }
            }
        }
        xs->Add(dsSchema);
        return type;
    }
    
    
    inline DataSet3::VIEW_MARKS_GROUPDataTable::VIEW_MARKS_GROUPDataTable() {
        this->TableName = L"VIEW_MARKS_GROUP";
        this->BeginInit();
        this->InitClass();
        this->EndInit();
    }
    
    inline DataSet3::VIEW_MARKS_GROUPDataTable::VIEW_MARKS_GROUPDataTable(::System::Data::DataTable^  table) {
        this->TableName = table->TableName;
        if (table->CaseSensitive != table->DataSet->CaseSensitive) {
            this->CaseSensitive = table->CaseSensitive;
        }
        if (table->Locale->ToString() != table->DataSet->Locale->ToString()) {
            this->Locale = table->Locale;
        }
        if (table->Namespace != table->DataSet->Namespace) {
            this->Namespace = table->Namespace;
        }
        this->Prefix = table->Prefix;
        this->MinimumCapacity = table->MinimumCapacity;
    }
    
    inline DataSet3::VIEW_MARKS_GROUPDataTable::VIEW_MARKS_GROUPDataTable(::System::Runtime::Serialization::SerializationInfo^  info, 
                ::System::Runtime::Serialization::StreamingContext context) : 
            ::System::Data::DataTable(info, context) {
        this->InitVars();
    }
    
    inline ::System::Data::DataColumn^  DataSet3::VIEW_MARKS_GROUPDataTable::COURSEColumn::get() {
        return this->columnCOURSE;
    }
    
    inline ::System::Data::DataColumn^  DataSet3::VIEW_MARKS_GROUPDataTable::FULLNAMEColumn::get() {
        return this->columnFULLNAME;
    }
    
    inline ::System::Data::DataColumn^  DataSet3::VIEW_MARKS_GROUPDataTable::VALUE_MARKColumn::get() {
        return this->columnVALUE_MARK;
    }
    
    inline ::System::Data::DataColumn^  DataSet3::VIEW_MARKS_GROUPDataTable::DATE_MARKColumn::get() {
        return this->columnDATE_MARK;
    }
    
    inline ::System::Data::DataColumn^  DataSet3::VIEW_MARKS_GROUPDataTable::DISCNAMEColumn::get() {
        return this->columnDISCNAME;
    }
    
    inline ::System::Data::DataColumn^  DataSet3::VIEW_MARKS_GROUPDataTable::GROUPNAMEColumn::get() {
        return this->columnGROUPNAME;
    }
    
    inline ::System::Int32 DataSet3::VIEW_MARKS_GROUPDataTable::Count::get() {
        return this->Rows->Count;
    }
    
    inline dekan::DataSet3::VIEW_MARKS_GROUPRow^  DataSet3::VIEW_MARKS_GROUPDataTable::default::get(::System::Int32 index) {
        return (cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPRow^  >(this->Rows[index]));
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPDataTable::AddVIEW_MARKS_GROUPRow(dekan::DataSet3::VIEW_MARKS_GROUPRow^  row) {
        this->Rows->Add(row);
    }
    
    inline dekan::DataSet3::VIEW_MARKS_GROUPRow^  DataSet3::VIEW_MARKS_GROUPDataTable::AddVIEW_MARKS_GROUPRow(
                System::Decimal COURSE, 
                System::String^  FULLNAME, 
                System::Decimal VALUE_MARK, 
                System::DateTime DATE_MARK, 
                System::String^  DISCNAME, 
                System::String^  GROUPNAME) {
        dekan::DataSet3::VIEW_MARKS_GROUPRow^  rowVIEW_MARKS_GROUPRow = (cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPRow^  >(this->NewRow()));
        cli::array< ::System::Object^  >^  columnValuesArray = gcnew cli::array< ::System::Object^  >(6) {COURSE, FULLNAME, VALUE_MARK, 
            DATE_MARK, DISCNAME, GROUPNAME};
        rowVIEW_MARKS_GROUPRow->ItemArray = columnValuesArray;
        this->Rows->Add(rowVIEW_MARKS_GROUPRow);
        return rowVIEW_MARKS_GROUPRow;
    }
    
    inline ::System::Collections::IEnumerator^  DataSet3::VIEW_MARKS_GROUPDataTable::GetEnumerator() {
        return this->Rows->GetEnumerator();
    }
    
    inline ::System::Data::DataTable^  DataSet3::VIEW_MARKS_GROUPDataTable::Clone() {
        dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  cln = (cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  >(__super::Clone()));
        cln->InitVars();
        return cln;
    }
    
    inline ::System::Data::DataTable^  DataSet3::VIEW_MARKS_GROUPDataTable::CreateInstance() {
        return (gcnew dekan::DataSet3::VIEW_MARKS_GROUPDataTable());
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPDataTable::InitVars() {
        this->columnCOURSE = __super::Columns[L"COURSE"];
        this->columnFULLNAME = __super::Columns[L"FULLNAME"];
        this->columnVALUE_MARK = __super::Columns[L"VALUE_MARK"];
        this->columnDATE_MARK = __super::Columns[L"DATE_MARK"];
        this->columnDISCNAME = __super::Columns[L"DISCNAME"];
        this->columnGROUPNAME = __super::Columns[L"GROUPNAME"];
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPDataTable::InitClass() {
        this->columnCOURSE = (gcnew ::System::Data::DataColumn(L"COURSE", ::System::Decimal::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnCOURSE);
        this->columnFULLNAME = (gcnew ::System::Data::DataColumn(L"FULLNAME", ::System::String::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnFULLNAME);
        this->columnVALUE_MARK = (gcnew ::System::Data::DataColumn(L"VALUE_MARK", ::System::Decimal::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnVALUE_MARK);
        this->columnDATE_MARK = (gcnew ::System::Data::DataColumn(L"DATE_MARK", ::System::DateTime::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnDATE_MARK);
        this->columnDISCNAME = (gcnew ::System::Data::DataColumn(L"DISCNAME", ::System::String::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnDISCNAME);
        this->columnGROUPNAME = (gcnew ::System::Data::DataColumn(L"GROUPNAME", ::System::String::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnGROUPNAME);
        this->columnFULLNAME->MaxLength = 4000;
        this->columnDISCNAME->MaxLength = 4000;
        this->columnGROUPNAME->MaxLength = 4000;
    }
    
    inline dekan::DataSet3::VIEW_MARKS_GROUPRow^  DataSet3::VIEW_MARKS_GROUPDataTable::NewVIEW_MARKS_GROUPRow() {
        return (cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPRow^  >(this->NewRow()));
    }
    
    inline ::System::Data::DataRow^  DataSet3::VIEW_MARKS_GROUPDataTable::NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) {
        return (gcnew dekan::DataSet3::VIEW_MARKS_GROUPRow(builder));
    }
    
    inline ::System::Type^  DataSet3::VIEW_MARKS_GROUPDataTable::GetRowType() {
        return dekan::DataSet3::VIEW_MARKS_GROUPRow::typeid;
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPDataTable::OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanged(e);
        {
            this->VIEW_MARKS_GROUPRowChanged(this, (gcnew dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEvent((cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPDataTable::OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanging(e);
        {
            this->VIEW_MARKS_GROUPRowChanging(this, (gcnew dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEvent((cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPDataTable::OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleted(e);
        {
            this->VIEW_MARKS_GROUPRowDeleted(this, (gcnew dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEvent((cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPDataTable::OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleting(e);
        {
            this->VIEW_MARKS_GROUPRowDeleting(this, (gcnew dekan::DataSet3::VIEW_MARKS_GROUPRowChangeEvent((cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPDataTable::RemoveVIEW_MARKS_GROUPRow(dekan::DataSet3::VIEW_MARKS_GROUPRow^  row) {
        this->Rows->Remove(row);
    }
    
    inline ::System::Xml::Schema::XmlSchemaComplexType^  DataSet3::VIEW_MARKS_GROUPDataTable::GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
        ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
        ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
        dekan::DataSet3^  ds = (gcnew dekan::DataSet3());
        ::System::Xml::Schema::XmlSchemaAny^  any1 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any1->Namespace = L"http://www.w3.org/2001/XMLSchema";
        any1->MinOccurs = ::System::Decimal(0);
        any1->MaxOccurs = ::System::Decimal::MaxValue;
        any1->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any1);
        ::System::Xml::Schema::XmlSchemaAny^  any2 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any2->Namespace = L"urn:schemas-microsoft-com:xml-diffgram-v1";
        any2->MinOccurs = ::System::Decimal(1);
        any2->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any2);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute1 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute1->Name = L"namespace";
        attribute1->FixedValue = ds->Namespace;
        type->Attributes->Add(attribute1);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute2 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute2->Name = L"tableTypeName";
        attribute2->FixedValue = L"VIEW_MARKS_GROUPDataTable";
        type->Attributes->Add(attribute2);
        type->Particle = sequence;
        ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
        if (xs->Contains(dsSchema->TargetNamespace)) {
            ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
            ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
            try {
                ::System::Xml::Schema::XmlSchema^  schema = nullptr;
                dsSchema->Write(s1);
                for (                ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();                 ) {
                    schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                    s2->SetLength(0);
                    schema->Write(s2);
                    if (s1->Length == s2->Length) {
                        s1->Position = 0;
                        s2->Position = 0;
                        for (                        ; ((s1->Position != s1->Length) 
                                    && (s1->ReadByte() == s2->ReadByte()));                         ) {
                            ;
                        }
                        if (s1->Position == s1->Length) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if (s1 != nullptr) {
                    s1->Close();
                }
                if (s2 != nullptr) {
                    s2->Close();
                }
            }
        }
        xs->Add(dsSchema);
        return type;
    }
    
    
    inline DataSet3::GROUPSRow::GROUPSRow(::System::Data::DataRowBuilder^  rb) : 
            ::System::Data::DataRow(rb) {
        this->tableGROUPS = (cli::safe_cast<dekan::DataSet3::GROUPSDataTable^  >(this->Table));
    }
    
    inline System::Decimal DataSet3::GROUPSRow::ID_GROUP::get() {
        return (cli::safe_cast<::System::Decimal >(this[this->tableGROUPS->ID_GROUPColumn]));
    }
    inline System::Void DataSet3::GROUPSRow::ID_GROUP::set(System::Decimal value) {
        this[this->tableGROUPS->ID_GROUPColumn] = value;
    }
    
    inline System::String^  DataSet3::GROUPSRow::GROUPNAME::get() {
        try {
            return (cli::safe_cast<::System::String^  >(this[this->tableGROUPS->GROUPNAMEColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'GROUPNAME\' в таблице \'GROUPS\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet3::GROUPSRow::GROUPNAME::set(System::String^  value) {
        this[this->tableGROUPS->GROUPNAMEColumn] = value;
    }
    
    inline ::System::Boolean DataSet3::GROUPSRow::IsGROUPNAMENull() {
        return this->IsNull(this->tableGROUPS->GROUPNAMEColumn);
    }
    
    inline ::System::Void DataSet3::GROUPSRow::SetGROUPNAMENull() {
        this[this->tableGROUPS->GROUPNAMEColumn] = ::System::Convert::DBNull;
    }
    
    
    inline DataSet3::VIEW_MARKS_GROUPRow::VIEW_MARKS_GROUPRow(::System::Data::DataRowBuilder^  rb) : 
            ::System::Data::DataRow(rb) {
        this->tableVIEW_MARKS_GROUP = (cli::safe_cast<dekan::DataSet3::VIEW_MARKS_GROUPDataTable^  >(this->Table));
    }
    
    inline System::Decimal DataSet3::VIEW_MARKS_GROUPRow::COURSE::get() {
        try {
            return (cli::safe_cast<::System::Decimal >(this[this->tableVIEW_MARKS_GROUP->COURSEColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'COURSE\' в таблице \'VIEW_MARKS_GROUP\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet3::VIEW_MARKS_GROUPRow::COURSE::set(System::Decimal value) {
        this[this->tableVIEW_MARKS_GROUP->COURSEColumn] = value;
    }
    
    inline System::String^  DataSet3::VIEW_MARKS_GROUPRow::FULLNAME::get() {
        try {
            return (cli::safe_cast<::System::String^  >(this[this->tableVIEW_MARKS_GROUP->FULLNAMEColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'FULLNAME\' в таблице \'VIEW_MARKS_GROUP\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet3::VIEW_MARKS_GROUPRow::FULLNAME::set(System::String^  value) {
        this[this->tableVIEW_MARKS_GROUP->FULLNAMEColumn] = value;
    }
    
    inline System::Decimal DataSet3::VIEW_MARKS_GROUPRow::VALUE_MARK::get() {
        try {
            return (cli::safe_cast<::System::Decimal >(this[this->tableVIEW_MARKS_GROUP->VALUE_MARKColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'VALUE_MARK\' в таблице \'VIEW_MARKS_GROUP\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet3::VIEW_MARKS_GROUPRow::VALUE_MARK::set(System::Decimal value) {
        this[this->tableVIEW_MARKS_GROUP->VALUE_MARKColumn] = value;
    }
    
    inline System::DateTime DataSet3::VIEW_MARKS_GROUPRow::DATE_MARK::get() {
        try {
            return (cli::safe_cast<::System::DateTime >(this[this->tableVIEW_MARKS_GROUP->DATE_MARKColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'DATE_MARK\' в таблице \'VIEW_MARKS_GROUP\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet3::VIEW_MARKS_GROUPRow::DATE_MARK::set(System::DateTime value) {
        this[this->tableVIEW_MARKS_GROUP->DATE_MARKColumn] = value;
    }
    
    inline System::String^  DataSet3::VIEW_MARKS_GROUPRow::DISCNAME::get() {
        try {
            return (cli::safe_cast<::System::String^  >(this[this->tableVIEW_MARKS_GROUP->DISCNAMEColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'DISCNAME\' в таблице \'VIEW_MARKS_GROUP\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet3::VIEW_MARKS_GROUPRow::DISCNAME::set(System::String^  value) {
        this[this->tableVIEW_MARKS_GROUP->DISCNAMEColumn] = value;
    }
    
    inline System::String^  DataSet3::VIEW_MARKS_GROUPRow::GROUPNAME::get() {
        try {
            return (cli::safe_cast<::System::String^  >(this[this->tableVIEW_MARKS_GROUP->GROUPNAMEColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'GROUPNAME\' в таблице \'VIEW_MARKS_GROUP\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet3::VIEW_MARKS_GROUPRow::GROUPNAME::set(System::String^  value) {
        this[this->tableVIEW_MARKS_GROUP->GROUPNAMEColumn] = value;
    }
    
    inline ::System::Boolean DataSet3::VIEW_MARKS_GROUPRow::IsCOURSENull() {
        return this->IsNull(this->tableVIEW_MARKS_GROUP->COURSEColumn);
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPRow::SetCOURSENull() {
        this[this->tableVIEW_MARKS_GROUP->COURSEColumn] = ::System::Convert::DBNull;
    }
    
    inline ::System::Boolean DataSet3::VIEW_MARKS_GROUPRow::IsFULLNAMENull() {
        return this->IsNull(this->tableVIEW_MARKS_GROUP->FULLNAMEColumn);
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPRow::SetFULLNAMENull() {
        this[this->tableVIEW_MARKS_GROUP->FULLNAMEColumn] = ::System::Convert::DBNull;
    }
    
    inline ::System::Boolean DataSet3::VIEW_MARKS_GROUPRow::IsVALUE_MARKNull() {
        return this->IsNull(this->tableVIEW_MARKS_GROUP->VALUE_MARKColumn);
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPRow::SetVALUE_MARKNull() {
        this[this->tableVIEW_MARKS_GROUP->VALUE_MARKColumn] = ::System::Convert::DBNull;
    }
    
    inline ::System::Boolean DataSet3::VIEW_MARKS_GROUPRow::IsDATE_MARKNull() {
        return this->IsNull(this->tableVIEW_MARKS_GROUP->DATE_MARKColumn);
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPRow::SetDATE_MARKNull() {
        this[this->tableVIEW_MARKS_GROUP->DATE_MARKColumn] = ::System::Convert::DBNull;
    }
    
    inline ::System::Boolean DataSet3::VIEW_MARKS_GROUPRow::IsDISCNAMENull() {
        return this->IsNull(this->tableVIEW_MARKS_GROUP->DISCNAMEColumn);
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPRow::SetDISCNAMENull() {
        this[this->tableVIEW_MARKS_GROUP->DISCNAMEColumn] = ::System::Convert::DBNull;
    }
    
    inline ::System::Boolean DataSet3::VIEW_MARKS_GROUPRow::IsGROUPNAMENull() {
        return this->IsNull(this->tableVIEW_MARKS_GROUP->GROUPNAMEColumn);
    }
    
    inline ::System::Void DataSet3::VIEW_MARKS_GROUPRow::SetGROUPNAMENull() {
        this[this->tableVIEW_MARKS_GROUP->GROUPNAMEColumn] = ::System::Convert::DBNull;
    }
    
    
    inline DataSet3::GROUPSRowChangeEvent::GROUPSRowChangeEvent(dekan::DataSet3::GROUPSRow^  row, ::System::Data::DataRowAction action) {
        this->eventRow = row;
        this->eventAction = action;
    }
    
    inline dekan::DataSet3::GROUPSRow^  DataSet3::GROUPSRowChangeEvent::Row::get() {
        return this->eventRow;
    }
    
    inline ::System::Data::DataRowAction DataSet3::GROUPSRowChangeEvent::Action::get() {
        return this->eventAction;
    }
    
    
    inline DataSet3::VIEW_MARKS_GROUPRowChangeEvent::VIEW_MARKS_GROUPRowChangeEvent(dekan::DataSet3::VIEW_MARKS_GROUPRow^  row, 
                ::System::Data::DataRowAction action) {
        this->eventRow = row;
        this->eventAction = action;
    }
    
    inline dekan::DataSet3::VIEW_MARKS_GROUPRow^  DataSet3::VIEW_MARKS_GROUPRowChangeEvent::Row::get() {
        return this->eventRow;
    }
    
    inline ::System::Data::DataRowAction DataSet3::VIEW_MARKS_GROUPRowChangeEvent::Action::get() {
        return this->eventAction;
    }
}
