#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Data.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace dekan {
    using namespace System;
    ref class DataSet6;
    
    
    /// <summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0"), 
    System::Serializable, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::ComponentModel::ToolboxItem(true), 
    System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedDataSetSchema"), 
    System::Xml::Serialization::XmlRootAttribute(L"DataSet6"), 
    System::ComponentModel::Design::HelpKeywordAttribute(L"vs.data.DataSet")]
    public ref class DataSet6 : public ::System::Data::DataSet {
        public : ref class GROUPSDataTable;
        public : ref class TableDataTable;
        public : ref class GROUPSRow;
        public : ref class TableRow;
        public : ref class GROUPSRowChangeEvent;
        public : ref class TableRowChangeEvent;
        
        private: dekan::DataSet6::GROUPSDataTable^  tableGROUPS;
        
        private: dekan::DataSet6::TableDataTable^  tableTable;
        
        private: ::System::Data::SchemaSerializationMode _schemaSerializationMode;
        
        public : delegate System::Void GROUPSRowChangeEventHandler(::System::Object^  sender, dekan::DataSet6::GROUPSRowChangeEvent^  e);
        
        public : delegate System::Void TableRowChangeEventHandler(::System::Object^  sender, dekan::DataSet6::TableRowChangeEvent^  e);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        DataSet6();
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        DataSet6(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::Browsable(false), 
        System::ComponentModel::DesignerSerializationVisibility(::System::ComponentModel::DesignerSerializationVisibility::Content)]
        property dekan::DataSet6::GROUPSDataTable^  GROUPS {
            dekan::DataSet6::GROUPSDataTable^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::Browsable(false), 
        System::ComponentModel::DesignerSerializationVisibility(::System::ComponentModel::DesignerSerializationVisibility::Content)]
        property dekan::DataSet6::TableDataTable^  Table {
            dekan::DataSet6::TableDataTable^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::BrowsableAttribute(true), 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Visible)]
        virtual property ::System::Data::SchemaSerializationMode SchemaSerializationMode {
            ::System::Data::SchemaSerializationMode get() override;
            System::Void set(::System::Data::SchemaSerializationMode value) override;
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Hidden)]
        property ::System::Data::DataTableCollection^  Tables {
            ::System::Data::DataTableCollection^  get() new;
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Hidden)]
        property ::System::Data::DataRelationCollection^  Relations {
            ::System::Data::DataRelationCollection^  get() new;
        }
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Void InitializeDerivedDataSet() override;
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Data::DataSet^  Clone() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Boolean ShouldSerializeTables() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Boolean ShouldSerializeRelations() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Void ReadXmlSerializable(::System::Xml::XmlReader^  reader) override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        virtual ::System::Xml::Schema::XmlSchema^  GetSchemaSerializable() override;
        
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Void InitVars();
        
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Void InitVars(::System::Boolean initTable);
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Void InitClass();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Boolean ShouldSerializeGROUPS();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Boolean ShouldSerializeTable();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        ::System::Void SchemaChanged(::System::Object^  sender, ::System::ComponentModel::CollectionChangeEventArgs^  e);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedDataSetSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
        
        public : /// <summary>
///Represents the strongly named DataTable class.
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0"), 
        System::Serializable, 
        System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedTableSchema")]
        ref class GROUPSDataTable : public ::System::Data::DataTable, public ::System::Collections::IEnumerable {
            
            private: ::System::Data::DataColumn^  columnID_STUDENT;
            
            private: ::System::Data::DataColumn^  columnFULLNAME;
            
            private: ::System::Data::DataColumn^  columnCOURSE;
            
            public: event dekan::DataSet6::GROUPSRowChangeEventHandler^  GROUPSRowChanging;
            
            public: event dekan::DataSet6::GROUPSRowChangeEventHandler^  GROUPSRowChanged;
            
            public: event dekan::DataSet6::GROUPSRowChangeEventHandler^  GROUPSRowDeleting;
            
            public: event dekan::DataSet6::GROUPSRowChangeEventHandler^  GROUPSRowDeleted;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSDataTable();
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSDataTable(::System::Data::DataTable^  table);
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  ID_STUDENTColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  FULLNAMEColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  COURSEColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::ComponentModel::Browsable(false)]
            property ::System::Int32 Count {
                ::System::Int32 get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property dekan::DataSet6::GROUPSRow^  default [::System::Int32 ] {
                dekan::DataSet6::GROUPSRow^  get(::System::Int32 index);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void AddGROUPSRow(dekan::DataSet6::GROUPSRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet6::GROUPSRow^  AddGROUPSRow(System::Decimal ID_STUDENT, System::String^  FULLNAME, System::Decimal COURSE);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet6::GROUPSRow^  FindByID_STUDENT(System::Decimal ID_STUDENT);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Collections::IEnumerator^  GetEnumerator();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataTable^  Clone() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataTable^  CreateInstance() override;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void InitVars();
            
            private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void InitClass();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet6::GROUPSRow^  NewGROUPSRow();
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataRow^  NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Type^  GetRowType() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) override;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void RemoveGROUPSRow(dekan::DataSet6::GROUPSRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
        };
        
        public : /// <summary>
///Represents the strongly named DataTable class.
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0"), 
        System::Serializable, 
        System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedTableSchema")]
        ref class TableDataTable : public ::System::Data::DataTable, public ::System::Collections::IEnumerable {
            
            private: ::System::Data::DataColumn^  columnID_GROUP;
            
            private: ::System::Data::DataColumn^  columnGROUPNAME;
            
            public: event dekan::DataSet6::TableRowChangeEventHandler^  TableRowChanging;
            
            public: event dekan::DataSet6::TableRowChangeEventHandler^  TableRowChanged;
            
            public: event dekan::DataSet6::TableRowChangeEventHandler^  TableRowDeleting;
            
            public: event dekan::DataSet6::TableRowChangeEventHandler^  TableRowDeleted;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            TableDataTable();
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            TableDataTable(::System::Data::DataTable^  table);
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            TableDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  ID_GROUPColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataColumn^  GROUPNAMEColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::ComponentModel::Browsable(false)]
            property ::System::Int32 Count {
                ::System::Int32 get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property dekan::DataSet6::TableRow^  default [::System::Int32 ] {
                dekan::DataSet6::TableRow^  get(::System::Int32 index);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void AddTableRow(dekan::DataSet6::TableRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet6::TableRow^  AddTableRow(System::Decimal ID_GROUP, System::String^  GROUPNAME);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet6::TableRow^  FindByID_GROUP(System::Decimal ID_GROUP);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Collections::IEnumerator^  GetEnumerator();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataTable^  Clone() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataTable^  CreateInstance() override;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void InitVars();
            
            private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void InitClass();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            dekan::DataSet6::TableRow^  NewTableRow();
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Data::DataRow^  NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Type^  GetRowType() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            virtual ::System::Void OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) override;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void RemoveTableRow(dekan::DataSet6::TableRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
        };
        
        public : /// <summary>
///Represents strongly named DataRow class.
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0")]
        ref class GROUPSRow : public ::System::Data::DataRow {
            
            private: dekan::DataSet6::GROUPSDataTable^  tableGROUPS;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSRow(::System::Data::DataRowBuilder^  rb);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::Decimal ID_STUDENT {
                System::Decimal get();
                System::Void set(System::Decimal value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::String^  FULLNAME {
                System::String^  get();
                System::Void set(System::String^  value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::Decimal COURSE {
                System::Decimal get();
                System::Void set(System::Decimal value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsFULLNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetFULLNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsCOURSENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetCOURSENull();
        };
        
        public : /// <summary>
///Represents strongly named DataRow class.
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0")]
        ref class TableRow : public ::System::Data::DataRow {
            
            private: dekan::DataSet6::TableDataTable^  tableTable;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            TableRow(::System::Data::DataRowBuilder^  rb);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::Decimal ID_GROUP {
                System::Decimal get();
                System::Void set(System::Decimal value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property System::String^  GROUPNAME {
                System::String^  get();
                System::Void set(System::String^  value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Boolean IsGROUPNAMENull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            ::System::Void SetGROUPNAMENull();
        };
        
        public : /// <summary>
///Row event argument class
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0")]
        ref class GROUPSRowChangeEvent : public ::System::EventArgs {
            
            private: dekan::DataSet6::GROUPSRow^  eventRow;
            
            private: ::System::Data::DataRowAction eventAction;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            GROUPSRowChangeEvent(dekan::DataSet6::GROUPSRow^  row, ::System::Data::DataRowAction action);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property dekan::DataSet6::GROUPSRow^  Row {
                dekan::DataSet6::GROUPSRow^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataRowAction Action {
                ::System::Data::DataRowAction get();
            }
        };
        
        public : /// <summary>
///Row event argument class
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"2.0.0.0")]
        ref class TableRowChangeEvent : public ::System::EventArgs {
            
            private: dekan::DataSet6::TableRow^  eventRow;
            
            private: ::System::Data::DataRowAction eventAction;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            TableRowChangeEvent(dekan::DataSet6::TableRow^  row, ::System::Data::DataRowAction action);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property dekan::DataSet6::TableRow^  Row {
                dekan::DataSet6::TableRow^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            property ::System::Data::DataRowAction Action {
                ::System::Data::DataRowAction get();
            }
        };
    };
}
namespace dekan {
    
    
    inline DataSet6::DataSet6() {
        this->BeginInit();
        this->InitClass();
        ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &dekan::DataSet6::SchemaChanged);
        __super::Tables->CollectionChanged += schemaChangedHandler;
        __super::Relations->CollectionChanged += schemaChangedHandler;
        this->EndInit();
    }
    
    inline DataSet6::DataSet6(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context) : 
            ::System::Data::DataSet(info, context, false) {
        if (this->IsBinarySerialized(info, context) == true) {
            this->InitVars(false);
            ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler1 = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &dekan::DataSet6::SchemaChanged);
            this->Tables->CollectionChanged += schemaChangedHandler1;
            this->Relations->CollectionChanged += schemaChangedHandler1;
            return;
        }
        ::System::String^  strSchema = (cli::safe_cast<::System::String^  >(info->GetValue(L"XmlSchema", ::System::String::typeid)));
        if (this->DetermineSchemaSerializationMode(info, context) == ::System::Data::SchemaSerializationMode::IncludeSchema) {
            ::System::Data::DataSet^  ds = (gcnew ::System::Data::DataSet());
            ds->ReadXmlSchema((gcnew ::System::Xml::XmlTextReader((gcnew ::System::IO::StringReader(strSchema)))));
            if (ds->Tables[L"GROUPS"] != nullptr) {
                __super::Tables->Add((gcnew dekan::DataSet6::GROUPSDataTable(ds->Tables[L"GROUPS"])));
            }
            if (ds->Tables[L"Table"] != nullptr) {
                __super::Tables->Add((gcnew dekan::DataSet6::TableDataTable(ds->Tables[L"Table"])));
            }
            this->DataSetName = ds->DataSetName;
            this->Prefix = ds->Prefix;
            this->Namespace = ds->Namespace;
            this->Locale = ds->Locale;
            this->CaseSensitive = ds->CaseSensitive;
            this->EnforceConstraints = ds->EnforceConstraints;
            this->Merge(ds, false, ::System::Data::MissingSchemaAction::Add);
            this->InitVars();
        }
        else {
            this->ReadXmlSchema((gcnew ::System::Xml::XmlTextReader((gcnew ::System::IO::StringReader(strSchema)))));
        }
        this->GetSerializationData(info, context);
        ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &dekan::DataSet6::SchemaChanged);
        __super::Tables->CollectionChanged += schemaChangedHandler;
        this->Relations->CollectionChanged += schemaChangedHandler;
    }
    
    inline dekan::DataSet6::GROUPSDataTable^  DataSet6::GROUPS::get() {
        return this->tableGROUPS;
    }
    
    inline dekan::DataSet6::TableDataTable^  DataSet6::Table::get() {
        return this->tableTable;
    }
    
    inline ::System::Data::SchemaSerializationMode DataSet6::SchemaSerializationMode::get() {
        return this->_schemaSerializationMode;
    }
    inline System::Void DataSet6::SchemaSerializationMode::set(::System::Data::SchemaSerializationMode value) {
        this->_schemaSerializationMode = __identifier(value);
    }
    
    inline ::System::Data::DataTableCollection^  DataSet6::Tables::get() {
        return __super::Tables;
    }
    
    inline ::System::Data::DataRelationCollection^  DataSet6::Relations::get() {
        return __super::Relations;
    }
    
    inline ::System::Void DataSet6::InitializeDerivedDataSet() {
        this->BeginInit();
        this->InitClass();
        this->EndInit();
    }
    
    inline ::System::Data::DataSet^  DataSet6::Clone() {
        dekan::DataSet6^  cln = (cli::safe_cast<dekan::DataSet6^  >(__super::Clone()));
        cln->InitVars();
        cln->SchemaSerializationMode = this->SchemaSerializationMode;
        return cln;
    }
    
    inline ::System::Boolean DataSet6::ShouldSerializeTables() {
        return false;
    }
    
    inline ::System::Boolean DataSet6::ShouldSerializeRelations() {
        return false;
    }
    
    inline ::System::Void DataSet6::ReadXmlSerializable(::System::Xml::XmlReader^  reader) {
        if (this->DetermineSchemaSerializationMode(reader) == ::System::Data::SchemaSerializationMode::IncludeSchema) {
            this->Reset();
            ::System::Data::DataSet^  ds = (gcnew ::System::Data::DataSet());
            ds->ReadXml(reader);
            if (ds->Tables[L"GROUPS"] != nullptr) {
                __super::Tables->Add((gcnew dekan::DataSet6::GROUPSDataTable(ds->Tables[L"GROUPS"])));
            }
            if (ds->Tables[L"Table"] != nullptr) {
                __super::Tables->Add((gcnew dekan::DataSet6::TableDataTable(ds->Tables[L"Table"])));
            }
            this->DataSetName = ds->DataSetName;
            this->Prefix = ds->Prefix;
            this->Namespace = ds->Namespace;
            this->Locale = ds->Locale;
            this->CaseSensitive = ds->CaseSensitive;
            this->EnforceConstraints = ds->EnforceConstraints;
            this->Merge(ds, false, ::System::Data::MissingSchemaAction::Add);
            this->InitVars();
        }
        else {
            this->ReadXml(reader);
            this->InitVars();
        }
    }
    
    inline ::System::Xml::Schema::XmlSchema^  DataSet6::GetSchemaSerializable() {
        ::System::IO::MemoryStream^  stream = (gcnew ::System::IO::MemoryStream());
        this->WriteXmlSchema((gcnew ::System::Xml::XmlTextWriter(stream, nullptr)));
        stream->Position = 0;
        return ::System::Xml::Schema::XmlSchema::Read((gcnew ::System::Xml::XmlTextReader(stream)), nullptr);
    }
    
    inline ::System::Void DataSet6::InitVars() {
        this->InitVars(true);
    }
    
    inline ::System::Void DataSet6::InitVars(::System::Boolean initTable) {
        this->tableGROUPS = (cli::safe_cast<dekan::DataSet6::GROUPSDataTable^  >(__super::Tables[L"GROUPS"]));
        if (initTable == true) {
            if (this->tableGROUPS != nullptr) {
                this->tableGROUPS->InitVars();
            }
        }
        this->tableTable = (cli::safe_cast<dekan::DataSet6::TableDataTable^  >(__super::Tables[L"Table"]));
        if (initTable == true) {
            if (this->tableTable != nullptr) {
                this->tableTable->InitVars();
            }
        }
    }
    
    inline ::System::Void DataSet6::InitClass() {
        this->DataSetName = L"DataSet6";
        this->Prefix = L"";
        this->Namespace = L"http://tempuri.org/DataSet6.xsd";
        this->EnforceConstraints = true;
        this->SchemaSerializationMode = ::System::Data::SchemaSerializationMode::IncludeSchema;
        this->tableGROUPS = (gcnew dekan::DataSet6::GROUPSDataTable());
        __super::Tables->Add(this->tableGROUPS);
        this->tableTable = (gcnew dekan::DataSet6::TableDataTable());
        __super::Tables->Add(this->tableTable);
    }
    
    inline ::System::Boolean DataSet6::ShouldSerializeGROUPS() {
        return false;
    }
    
    inline ::System::Boolean DataSet6::ShouldSerializeTable() {
        return false;
    }
    
    inline ::System::Void DataSet6::SchemaChanged(::System::Object^  sender, ::System::ComponentModel::CollectionChangeEventArgs^  e) {
        if (e->Action == ::System::ComponentModel::CollectionChangeAction::Remove) {
            this->InitVars();
        }
    }
    
    inline ::System::Xml::Schema::XmlSchemaComplexType^  DataSet6::GetTypedDataSetSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
        dekan::DataSet6^  ds = (gcnew dekan::DataSet6());
        ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
        ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
        ::System::Xml::Schema::XmlSchemaAny^  any = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any->Namespace = ds->Namespace;
        sequence->Items->Add(any);
        type->Particle = sequence;
        ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
        if (xs->Contains(dsSchema->TargetNamespace)) {
            ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
            ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
            try {
                ::System::Xml::Schema::XmlSchema^  schema = nullptr;
                dsSchema->Write(s1);
                for (                ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();                 ) {
                    schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                    s2->SetLength(0);
                    schema->Write(s2);
                    if (s1->Length == s2->Length) {
                        s1->Position = 0;
                        s2->Position = 0;
                        for (                        ; ((s1->Position != s1->Length) 
                                    && (s1->ReadByte() == s2->ReadByte()));                         ) {
                            ;
                        }
                        if (s1->Position == s1->Length) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if (s1 != nullptr) {
                    s1->Close();
                }
                if (s2 != nullptr) {
                    s2->Close();
                }
            }
        }
        xs->Add(dsSchema);
        return type;
    }
    
    
    inline DataSet6::GROUPSDataTable::GROUPSDataTable() {
        this->TableName = L"GROUPS";
        this->BeginInit();
        this->InitClass();
        this->EndInit();
    }
    
    inline DataSet6::GROUPSDataTable::GROUPSDataTable(::System::Data::DataTable^  table) {
        this->TableName = table->TableName;
        if (table->CaseSensitive != table->DataSet->CaseSensitive) {
            this->CaseSensitive = table->CaseSensitive;
        }
        if (table->Locale->ToString() != table->DataSet->Locale->ToString()) {
            this->Locale = table->Locale;
        }
        if (table->Namespace != table->DataSet->Namespace) {
            this->Namespace = table->Namespace;
        }
        this->Prefix = table->Prefix;
        this->MinimumCapacity = table->MinimumCapacity;
    }
    
    inline DataSet6::GROUPSDataTable::GROUPSDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context) : 
            ::System::Data::DataTable(info, context) {
        this->InitVars();
    }
    
    inline ::System::Data::DataColumn^  DataSet6::GROUPSDataTable::ID_STUDENTColumn::get() {
        return this->columnID_STUDENT;
    }
    
    inline ::System::Data::DataColumn^  DataSet6::GROUPSDataTable::FULLNAMEColumn::get() {
        return this->columnFULLNAME;
    }
    
    inline ::System::Data::DataColumn^  DataSet6::GROUPSDataTable::COURSEColumn::get() {
        return this->columnCOURSE;
    }
    
    inline ::System::Int32 DataSet6::GROUPSDataTable::Count::get() {
        return this->Rows->Count;
    }
    
    inline dekan::DataSet6::GROUPSRow^  DataSet6::GROUPSDataTable::default::get(::System::Int32 index) {
        return (cli::safe_cast<dekan::DataSet6::GROUPSRow^  >(this->Rows[index]));
    }
    
    inline ::System::Void DataSet6::GROUPSDataTable::AddGROUPSRow(dekan::DataSet6::GROUPSRow^  row) {
        this->Rows->Add(row);
    }
    
    inline dekan::DataSet6::GROUPSRow^  DataSet6::GROUPSDataTable::AddGROUPSRow(System::Decimal ID_STUDENT, System::String^  FULLNAME, 
                System::Decimal COURSE) {
        dekan::DataSet6::GROUPSRow^  rowGROUPSRow = (cli::safe_cast<dekan::DataSet6::GROUPSRow^  >(this->NewRow()));
        cli::array< ::System::Object^  >^  columnValuesArray = gcnew cli::array< ::System::Object^  >(3) {ID_STUDENT, FULLNAME, 
            COURSE};
        rowGROUPSRow->ItemArray = columnValuesArray;
        this->Rows->Add(rowGROUPSRow);
        return rowGROUPSRow;
    }
    
    inline dekan::DataSet6::GROUPSRow^  DataSet6::GROUPSDataTable::FindByID_STUDENT(System::Decimal ID_STUDENT) {
        return (cli::safe_cast<dekan::DataSet6::GROUPSRow^  >(this->Rows->Find(gcnew cli::array< System::Object^  >(1) {ID_STUDENT})));
    }
    
    inline ::System::Collections::IEnumerator^  DataSet6::GROUPSDataTable::GetEnumerator() {
        return this->Rows->GetEnumerator();
    }
    
    inline ::System::Data::DataTable^  DataSet6::GROUPSDataTable::Clone() {
        dekan::DataSet6::GROUPSDataTable^  cln = (cli::safe_cast<dekan::DataSet6::GROUPSDataTable^  >(__super::Clone()));
        cln->InitVars();
        return cln;
    }
    
    inline ::System::Data::DataTable^  DataSet6::GROUPSDataTable::CreateInstance() {
        return (gcnew dekan::DataSet6::GROUPSDataTable());
    }
    
    inline ::System::Void DataSet6::GROUPSDataTable::InitVars() {
        this->columnID_STUDENT = __super::Columns[L"ID_STUDENT"];
        this->columnFULLNAME = __super::Columns[L"FULLNAME"];
        this->columnCOURSE = __super::Columns[L"COURSE"];
    }
    
    inline ::System::Void DataSet6::GROUPSDataTable::InitClass() {
        this->columnID_STUDENT = (gcnew ::System::Data::DataColumn(L"ID_STUDENT", ::System::Decimal::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnID_STUDENT);
        this->columnFULLNAME = (gcnew ::System::Data::DataColumn(L"FULLNAME", ::System::String::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnFULLNAME);
        this->columnCOURSE = (gcnew ::System::Data::DataColumn(L"COURSE", ::System::Decimal::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnCOURSE);
        this->Constraints->Add((gcnew ::System::Data::UniqueConstraint(L"Constraint1", gcnew cli::array< ::System::Data::DataColumn^  >(1) {this->columnID_STUDENT}, 
                true)));
        this->columnID_STUDENT->AllowDBNull = false;
        this->columnID_STUDENT->Unique = true;
        this->columnFULLNAME->MaxLength = 4000;
    }
    
    inline dekan::DataSet6::GROUPSRow^  DataSet6::GROUPSDataTable::NewGROUPSRow() {
        return (cli::safe_cast<dekan::DataSet6::GROUPSRow^  >(this->NewRow()));
    }
    
    inline ::System::Data::DataRow^  DataSet6::GROUPSDataTable::NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) {
        return (gcnew dekan::DataSet6::GROUPSRow(builder));
    }
    
    inline ::System::Type^  DataSet6::GROUPSDataTable::GetRowType() {
        return dekan::DataSet6::GROUPSRow::typeid;
    }
    
    inline ::System::Void DataSet6::GROUPSDataTable::OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanged(e);
        {
            this->GROUPSRowChanged(this, (gcnew dekan::DataSet6::GROUPSRowChangeEvent((cli::safe_cast<dekan::DataSet6::GROUPSRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet6::GROUPSDataTable::OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanging(e);
        {
            this->GROUPSRowChanging(this, (gcnew dekan::DataSet6::GROUPSRowChangeEvent((cli::safe_cast<dekan::DataSet6::GROUPSRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet6::GROUPSDataTable::OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleted(e);
        {
            this->GROUPSRowDeleted(this, (gcnew dekan::DataSet6::GROUPSRowChangeEvent((cli::safe_cast<dekan::DataSet6::GROUPSRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet6::GROUPSDataTable::OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleting(e);
        {
            this->GROUPSRowDeleting(this, (gcnew dekan::DataSet6::GROUPSRowChangeEvent((cli::safe_cast<dekan::DataSet6::GROUPSRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet6::GROUPSDataTable::RemoveGROUPSRow(dekan::DataSet6::GROUPSRow^  row) {
        this->Rows->Remove(row);
    }
    
    inline ::System::Xml::Schema::XmlSchemaComplexType^  DataSet6::GROUPSDataTable::GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
        ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
        ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
        dekan::DataSet6^  ds = (gcnew dekan::DataSet6());
        ::System::Xml::Schema::XmlSchemaAny^  any1 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any1->Namespace = L"http://www.w3.org/2001/XMLSchema";
        any1->MinOccurs = ::System::Decimal(0);
        any1->MaxOccurs = ::System::Decimal::MaxValue;
        any1->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any1);
        ::System::Xml::Schema::XmlSchemaAny^  any2 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any2->Namespace = L"urn:schemas-microsoft-com:xml-diffgram-v1";
        any2->MinOccurs = ::System::Decimal(1);
        any2->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any2);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute1 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute1->Name = L"namespace";
        attribute1->FixedValue = ds->Namespace;
        type->Attributes->Add(attribute1);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute2 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute2->Name = L"tableTypeName";
        attribute2->FixedValue = L"GROUPSDataTable";
        type->Attributes->Add(attribute2);
        type->Particle = sequence;
        ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
        if (xs->Contains(dsSchema->TargetNamespace)) {
            ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
            ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
            try {
                ::System::Xml::Schema::XmlSchema^  schema = nullptr;
                dsSchema->Write(s1);
                for (                ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();                 ) {
                    schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                    s2->SetLength(0);
                    schema->Write(s2);
                    if (s1->Length == s2->Length) {
                        s1->Position = 0;
                        s2->Position = 0;
                        for (                        ; ((s1->Position != s1->Length) 
                                    && (s1->ReadByte() == s2->ReadByte()));                         ) {
                            ;
                        }
                        if (s1->Position == s1->Length) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if (s1 != nullptr) {
                    s1->Close();
                }
                if (s2 != nullptr) {
                    s2->Close();
                }
            }
        }
        xs->Add(dsSchema);
        return type;
    }
    
    
    inline DataSet6::TableDataTable::TableDataTable() {
        this->TableName = L"Table";
        this->BeginInit();
        this->InitClass();
        this->EndInit();
    }
    
    inline DataSet6::TableDataTable::TableDataTable(::System::Data::DataTable^  table) {
        this->TableName = table->TableName;
        if (table->CaseSensitive != table->DataSet->CaseSensitive) {
            this->CaseSensitive = table->CaseSensitive;
        }
        if (table->Locale->ToString() != table->DataSet->Locale->ToString()) {
            this->Locale = table->Locale;
        }
        if (table->Namespace != table->DataSet->Namespace) {
            this->Namespace = table->Namespace;
        }
        this->Prefix = table->Prefix;
        this->MinimumCapacity = table->MinimumCapacity;
    }
    
    inline DataSet6::TableDataTable::TableDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context) : 
            ::System::Data::DataTable(info, context) {
        this->InitVars();
    }
    
    inline ::System::Data::DataColumn^  DataSet6::TableDataTable::ID_GROUPColumn::get() {
        return this->columnID_GROUP;
    }
    
    inline ::System::Data::DataColumn^  DataSet6::TableDataTable::GROUPNAMEColumn::get() {
        return this->columnGROUPNAME;
    }
    
    inline ::System::Int32 DataSet6::TableDataTable::Count::get() {
        return this->Rows->Count;
    }
    
    inline dekan::DataSet6::TableRow^  DataSet6::TableDataTable::default::get(::System::Int32 index) {
        return (cli::safe_cast<dekan::DataSet6::TableRow^  >(this->Rows[index]));
    }
    
    inline ::System::Void DataSet6::TableDataTable::AddTableRow(dekan::DataSet6::TableRow^  row) {
        this->Rows->Add(row);
    }
    
    inline dekan::DataSet6::TableRow^  DataSet6::TableDataTable::AddTableRow(System::Decimal ID_GROUP, System::String^  GROUPNAME) {
        dekan::DataSet6::TableRow^  rowTableRow = (cli::safe_cast<dekan::DataSet6::TableRow^  >(this->NewRow()));
        cli::array< ::System::Object^  >^  columnValuesArray = gcnew cli::array< ::System::Object^  >(2) {ID_GROUP, GROUPNAME};
        rowTableRow->ItemArray = columnValuesArray;
        this->Rows->Add(rowTableRow);
        return rowTableRow;
    }
    
    inline dekan::DataSet6::TableRow^  DataSet6::TableDataTable::FindByID_GROUP(System::Decimal ID_GROUP) {
        return (cli::safe_cast<dekan::DataSet6::TableRow^  >(this->Rows->Find(gcnew cli::array< System::Object^  >(1) {ID_GROUP})));
    }
    
    inline ::System::Collections::IEnumerator^  DataSet6::TableDataTable::GetEnumerator() {
        return this->Rows->GetEnumerator();
    }
    
    inline ::System::Data::DataTable^  DataSet6::TableDataTable::Clone() {
        dekan::DataSet6::TableDataTable^  cln = (cli::safe_cast<dekan::DataSet6::TableDataTable^  >(__super::Clone()));
        cln->InitVars();
        return cln;
    }
    
    inline ::System::Data::DataTable^  DataSet6::TableDataTable::CreateInstance() {
        return (gcnew dekan::DataSet6::TableDataTable());
    }
    
    inline ::System::Void DataSet6::TableDataTable::InitVars() {
        this->columnID_GROUP = __super::Columns[L"ID_GROUP"];
        this->columnGROUPNAME = __super::Columns[L"GROUPNAME"];
    }
    
    inline ::System::Void DataSet6::TableDataTable::InitClass() {
        this->columnID_GROUP = (gcnew ::System::Data::DataColumn(L"ID_GROUP", ::System::Decimal::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnID_GROUP);
        this->columnGROUPNAME = (gcnew ::System::Data::DataColumn(L"GROUPNAME", ::System::String::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnGROUPNAME);
        this->Constraints->Add((gcnew ::System::Data::UniqueConstraint(L"Constraint1", gcnew cli::array< ::System::Data::DataColumn^  >(1) {this->columnID_GROUP}, 
                true)));
        this->columnID_GROUP->AllowDBNull = false;
        this->columnID_GROUP->Unique = true;
        this->columnGROUPNAME->MaxLength = 4000;
        this->ExtendedProperties->Add(L"Generator_RowClassName", L"TableRow");
        this->ExtendedProperties->Add(L"Generator_RowEvArgName", L"TableRowChangeEvent");
        this->ExtendedProperties->Add(L"Generator_RowEvHandlerName", L"TableRowChangeEventHandler");
        this->ExtendedProperties->Add(L"Generator_TableClassName", L"TableDataTable");
        this->ExtendedProperties->Add(L"Generator_TablePropName", L"Table");
        this->ExtendedProperties->Add(L"Generator_TableVarName", L"tableTable");
        this->ExtendedProperties->Add(L"Generator_UserTableName", L"Table");
    }
    
    inline dekan::DataSet6::TableRow^  DataSet6::TableDataTable::NewTableRow() {
        return (cli::safe_cast<dekan::DataSet6::TableRow^  >(this->NewRow()));
    }
    
    inline ::System::Data::DataRow^  DataSet6::TableDataTable::NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) {
        return (gcnew dekan::DataSet6::TableRow(builder));
    }
    
    inline ::System::Type^  DataSet6::TableDataTable::GetRowType() {
        return dekan::DataSet6::TableRow::typeid;
    }
    
    inline ::System::Void DataSet6::TableDataTable::OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanged(e);
        {
            this->TableRowChanged(this, (gcnew dekan::DataSet6::TableRowChangeEvent((cli::safe_cast<dekan::DataSet6::TableRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet6::TableDataTable::OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanging(e);
        {
            this->TableRowChanging(this, (gcnew dekan::DataSet6::TableRowChangeEvent((cli::safe_cast<dekan::DataSet6::TableRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet6::TableDataTable::OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleted(e);
        {
            this->TableRowDeleted(this, (gcnew dekan::DataSet6::TableRowChangeEvent((cli::safe_cast<dekan::DataSet6::TableRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet6::TableDataTable::OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleting(e);
        {
            this->TableRowDeleting(this, (gcnew dekan::DataSet6::TableRowChangeEvent((cli::safe_cast<dekan::DataSet6::TableRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void DataSet6::TableDataTable::RemoveTableRow(dekan::DataSet6::TableRow^  row) {
        this->Rows->Remove(row);
    }
    
    inline ::System::Xml::Schema::XmlSchemaComplexType^  DataSet6::TableDataTable::GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
        ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
        ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
        dekan::DataSet6^  ds = (gcnew dekan::DataSet6());
        ::System::Xml::Schema::XmlSchemaAny^  any1 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any1->Namespace = L"http://www.w3.org/2001/XMLSchema";
        any1->MinOccurs = ::System::Decimal(0);
        any1->MaxOccurs = ::System::Decimal::MaxValue;
        any1->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any1);
        ::System::Xml::Schema::XmlSchemaAny^  any2 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any2->Namespace = L"urn:schemas-microsoft-com:xml-diffgram-v1";
        any2->MinOccurs = ::System::Decimal(1);
        any2->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any2);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute1 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute1->Name = L"namespace";
        attribute1->FixedValue = ds->Namespace;
        type->Attributes->Add(attribute1);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute2 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute2->Name = L"tableTypeName";
        attribute2->FixedValue = L"TableDataTable";
        type->Attributes->Add(attribute2);
        type->Particle = sequence;
        ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
        if (xs->Contains(dsSchema->TargetNamespace)) {
            ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
            ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
            try {
                ::System::Xml::Schema::XmlSchema^  schema = nullptr;
                dsSchema->Write(s1);
                for (                ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();                 ) {
                    schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                    s2->SetLength(0);
                    schema->Write(s2);
                    if (s1->Length == s2->Length) {
                        s1->Position = 0;
                        s2->Position = 0;
                        for (                        ; ((s1->Position != s1->Length) 
                                    && (s1->ReadByte() == s2->ReadByte()));                         ) {
                            ;
                        }
                        if (s1->Position == s1->Length) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if (s1 != nullptr) {
                    s1->Close();
                }
                if (s2 != nullptr) {
                    s2->Close();
                }
            }
        }
        xs->Add(dsSchema);
        return type;
    }
    
    
    inline DataSet6::GROUPSRow::GROUPSRow(::System::Data::DataRowBuilder^  rb) : 
            ::System::Data::DataRow(rb) {
        this->tableGROUPS = (cli::safe_cast<dekan::DataSet6::GROUPSDataTable^  >(this->Table));
    }
    
    inline System::Decimal DataSet6::GROUPSRow::ID_STUDENT::get() {
        return (cli::safe_cast<::System::Decimal >(this[this->tableGROUPS->ID_STUDENTColumn]));
    }
    inline System::Void DataSet6::GROUPSRow::ID_STUDENT::set(System::Decimal value) {
        this[this->tableGROUPS->ID_STUDENTColumn] = value;
    }
    
    inline System::String^  DataSet6::GROUPSRow::FULLNAME::get() {
        try {
            return (cli::safe_cast<::System::String^  >(this[this->tableGROUPS->FULLNAMEColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'FULLNAME\' в таблице \'GROUPS\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet6::GROUPSRow::FULLNAME::set(System::String^  value) {
        this[this->tableGROUPS->FULLNAMEColumn] = value;
    }
    
    inline System::Decimal DataSet6::GROUPSRow::COURSE::get() {
        try {
            return (cli::safe_cast<::System::Decimal >(this[this->tableGROUPS->COURSEColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'COURSE\' в таблице \'GROUPS\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet6::GROUPSRow::COURSE::set(System::Decimal value) {
        this[this->tableGROUPS->COURSEColumn] = value;
    }
    
    inline ::System::Boolean DataSet6::GROUPSRow::IsFULLNAMENull() {
        return this->IsNull(this->tableGROUPS->FULLNAMEColumn);
    }
    
    inline ::System::Void DataSet6::GROUPSRow::SetFULLNAMENull() {
        this[this->tableGROUPS->FULLNAMEColumn] = ::System::Convert::DBNull;
    }
    
    inline ::System::Boolean DataSet6::GROUPSRow::IsCOURSENull() {
        return this->IsNull(this->tableGROUPS->COURSEColumn);
    }
    
    inline ::System::Void DataSet6::GROUPSRow::SetCOURSENull() {
        this[this->tableGROUPS->COURSEColumn] = ::System::Convert::DBNull;
    }
    
    
    inline DataSet6::TableRow::TableRow(::System::Data::DataRowBuilder^  rb) : 
            ::System::Data::DataRow(rb) {
        this->tableTable = (cli::safe_cast<dekan::DataSet6::TableDataTable^  >(this->Table));
    }
    
    inline System::Decimal DataSet6::TableRow::ID_GROUP::get() {
        return (cli::safe_cast<::System::Decimal >(this[this->tableTable->ID_GROUPColumn]));
    }
    inline System::Void DataSet6::TableRow::ID_GROUP::set(System::Decimal value) {
        this[this->tableTable->ID_GROUPColumn] = value;
    }
    
    inline System::String^  DataSet6::TableRow::GROUPNAME::get() {
        try {
            return (cli::safe_cast<::System::String^  >(this[this->tableTable->GROUPNAMEColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"Значение для столбца \'GROUPNAME\' в таблице \'Table\' равно DBNull.", 
                e));
        }
    }
    inline System::Void DataSet6::TableRow::GROUPNAME::set(System::String^  value) {
        this[this->tableTable->GROUPNAMEColumn] = value;
    }
    
    inline ::System::Boolean DataSet6::TableRow::IsGROUPNAMENull() {
        return this->IsNull(this->tableTable->GROUPNAMEColumn);
    }
    
    inline ::System::Void DataSet6::TableRow::SetGROUPNAMENull() {
        this[this->tableTable->GROUPNAMEColumn] = ::System::Convert::DBNull;
    }
    
    
    inline DataSet6::GROUPSRowChangeEvent::GROUPSRowChangeEvent(dekan::DataSet6::GROUPSRow^  row, ::System::Data::DataRowAction action) {
        this->eventRow = row;
        this->eventAction = action;
    }
    
    inline dekan::DataSet6::GROUPSRow^  DataSet6::GROUPSRowChangeEvent::Row::get() {
        return this->eventRow;
    }
    
    inline ::System::Data::DataRowAction DataSet6::GROUPSRowChangeEvent::Action::get() {
        return this->eventAction;
    }
    
    
    inline DataSet6::TableRowChangeEvent::TableRowChangeEvent(dekan::DataSet6::TableRow^  row, ::System::Data::DataRowAction action) {
        this->eventRow = row;
        this->eventAction = action;
    }
    
    inline dekan::DataSet6::TableRow^  DataSet6::TableRowChangeEvent::Row::get() {
        return this->eventRow;
    }
    
    inline ::System::Data::DataRowAction DataSet6::TableRowChangeEvent::Action::get() {
        return this->eventAction;
    }
}
