REM INSERTING into DEKANAT.DISCIPLINES
Insert into DEKANAT.DISCIPLINES (ID_DISCIPLINE,ID_DISCNAME,NUMBER_HOURS,ID_GROUP,ID_TYPE) values (1,-1,20,1,1);
Insert into DEKANAT.DISCIPLINES (ID_DISCIPLINE,ID_DISCNAME,NUMBER_HOURS,ID_GROUP,ID_TYPE) values (4,-1,20,5,1);
Insert into DEKANAT.DISCIPLINES (ID_DISCIPLINE,ID_DISCNAME,NUMBER_HOURS,ID_GROUP,ID_TYPE) values (5,2,25,1,2);
Insert into DEKANAT.DISCIPLINES (ID_DISCIPLINE,ID_DISCNAME,NUMBER_HOURS,ID_GROUP,ID_TYPE) values (6,2,25,5,2);
Insert into DEKANAT.DISCIPLINES (ID_DISCIPLINE,ID_DISCNAME,NUMBER_HOURS,ID_GROUP,ID_TYPE) values (7,-3,30,1,1);
Insert into DEKANAT.DISCIPLINES (ID_DISCIPLINE,ID_DISCNAME,NUMBER_HOURS,ID_GROUP,ID_TYPE) values (8,-3,90,1,1);
