REM INSERTING into DEKANAT.GROUPS
Insert into DEKANAT.GROUPS (ID_GROUP,NAME_GROUP,COURSE,ID_PROFESSION,SUBGROUP) values (1,'›œŒ',3,1,1);
Insert into DEKANAT.GROUPS (ID_GROUP,NAME_GROUP,COURSE,ID_PROFESSION,SUBGROUP) values (5,'›Ã',5,5,1);
Insert into DEKANAT.GROUPS (ID_GROUP,NAME_GROUP,COURSE,ID_PROFESSION,SUBGROUP) values (21,'»“',2,1,1);
