--------------------------------------------------------
--  Constraints for Table MARKS
--------------------------------------------------------

  ALTER TABLE "DEKANAT"."MARKS" ADD CONSTRAINT "MARKS_VALUE_CHECK" CHECK ((value_mark>=0)and(value_mark<=5)) ENABLE;
  ALTER TABLE "DEKANAT"."MARKS" ADD CONSTRAINT "marks PK" PRIMARY KEY ("ID_MARK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEKANAT"."MARKS" MODIFY ("ID_MARK" NOT NULL ENABLE);
