REM INSERTING into DEKANAT.MARKS_HISTORY
Insert into DEKANAT.MARKS_HISTORY (ID_MARK,VALUE_NEW_MARK,VALUE_OLD_MARK,DATE_MARK,ID_STUDENT,ID_NEW_TEACHER,ID_OLD_TEACHER,ID_DISCIPLINE) values (1,2,0,to_date('27-дей-11','DD-MON-RR'),4,2,2,1);
Insert into DEKANAT.MARKS_HISTORY (ID_MARK,VALUE_NEW_MARK,VALUE_OLD_MARK,DATE_MARK,ID_STUDENT,ID_NEW_TEACHER,ID_OLD_TEACHER,ID_DISCIPLINE) values (2,5,5,to_date('27-дей-11','DD-MON-RR'),24,1,1,1);
Insert into DEKANAT.MARKS_HISTORY (ID_MARK,VALUE_NEW_MARK,VALUE_OLD_MARK,DATE_MARK,ID_STUDENT,ID_NEW_TEACHER,ID_OLD_TEACHER,ID_DISCIPLINE) values (3,5,5,to_date('26-дей-11','DD-MON-RR'),24,2,1,4);
