REM INSERTING into DEKANAT.MARKS
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (1,5,to_date('25-дей-11','DD-MON-RR'),1,2,1);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (2,2,to_date('27-дей-11','DD-MON-RR'),4,2,1);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (23,0,null,16,1,6);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (22,0,null,12,1,6);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (24,0,null,12,2,4);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (25,0,null,16,2,4);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (26,5,to_date('26-дей-11','DD-MON-RR'),24,2,4);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (41,0,null,5,21,7);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (42,0,null,1,21,7);
Insert into DEKANAT.MARKS (ID_MARK,VALUE_MARK,DATE_MARK,ID_STUDENT,ID_TEACHER,ID_DISCIPLINE) values (43,0,null,4,21,7);
