--------------------------------------------------------
--  Ref Constraints for Table MARKS
--------------------------------------------------------

  ALTER TABLE "DEKANAT"."MARKS" ADD CONSTRAINT "STUDENTS2MARKS" FOREIGN KEY ("ID_STUDENT")
	  REFERENCES "DEKANAT"."STUDENTS" ("ID_STUDENT") ON DELETE SET NULL ENABLE;
  ALTER TABLE "DEKANAT"."MARKS" ADD CONSTRAINT "TEACHERS2MARKS" FOREIGN KEY ("ID_TEACHER")
	  REFERENCES "DEKANAT"."TEACHERS" ("ID_TEACHER") ON DELETE SET NULL ENABLE;
