--------------------------------------------------------
--  DDL for Table MARKS_HISTORY
--------------------------------------------------------

  CREATE TABLE "DEKANAT"."MARKS_HISTORY" 
   (	"ID_MARK" NUMBER(7,0), 
	"VALUE_NEW_MARK" NUMBER(1,0), 
	"VALUE_OLD_MARK" NUMBER(7,0), 
	"DATE_MARK" DATE, 
	"ID_STUDENT" NUMBER(7,0), 
	"ID_NEW_TEACHER" NUMBER(7,0), 
	"ID_OLD_TEACHER" NUMBER(7,0), 
	"ID_DISCIPLINE" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
