REM INSERTING into DEKANAT.STUDENTS
Insert into DEKANAT.STUDENTS (ID_STUDENT,LAST_NAME,FIRST_NAME,THIRD_NAME,BIRTHDAY,EXPIRY_STATUS,ENTER_DATE,ID_STATUS,ID_GROUP) values (5,'Веселов','Денис','Алексндрович',to_date('14-МАР-91','DD-MON-RR'),to_date('25-ДЕК-11','DD-MON-RR'),to_date('01-СЕН-09','DD-MON-RR'),1,1);
Insert into DEKANAT.STUDENTS (ID_STUDENT,LAST_NAME,FIRST_NAME,THIRD_NAME,BIRTHDAY,EXPIRY_STATUS,ENTER_DATE,ID_STATUS,ID_GROUP) values (1,'Баданин','Дмитрий','Александрович',to_date('05-НОЯ-91','DD-MON-RR'),to_date('25-ДЕК-11','DD-MON-RR'),to_date('01-СЕН-09','DD-MON-RR'),1,1);
Insert into DEKANAT.STUDENTS (ID_STUDENT,LAST_NAME,FIRST_NAME,THIRD_NAME,BIRTHDAY,EXPIRY_STATUS,ENTER_DATE,ID_STATUS,ID_GROUP) values (4,'Плотников','Евгений','Михайлович',to_date('01-ЯНВ-92','DD-MON-RR'),to_date('25-ДЕК-11','DD-MON-RR'),to_date('01-СЕН-09','DD-MON-RR'),1,1);
Insert into DEKANAT.STUDENTS (ID_STUDENT,LAST_NAME,FIRST_NAME,THIRD_NAME,BIRTHDAY,EXPIRY_STATUS,ENTER_DATE,ID_STATUS,ID_GROUP) values (9,'Фимичев','Николай','Николаевич',to_date('01-ЯНВ-92','DD-MON-RR'),to_date('25-ДЕК-11','DD-MON-RR'),to_date('01-СЕН-09','DD-MON-RR'),4,1);
Insert into DEKANAT.STUDENTS (ID_STUDENT,LAST_NAME,FIRST_NAME,THIRD_NAME,BIRTHDAY,EXPIRY_STATUS,ENTER_DATE,ID_STATUS,ID_GROUP) values (10,'Менухов','---','---',to_date('01-ЯНВ-90','DD-MON-RR'),to_date('05-МАР-10','DD-MON-RR'),to_date('01-СЕН-08','DD-MON-RR'),3,1);
Insert into DEKANAT.STUDENTS (ID_STUDENT,LAST_NAME,FIRST_NAME,THIRD_NAME,BIRTHDAY,EXPIRY_STATUS,ENTER_DATE,ID_STATUS,ID_GROUP) values (12,'Чистяков','Сергей','---',to_date('01-ЯНВ-92','DD-MON-RR'),to_date('25-ДЕК-11','DD-MON-RR'),to_date('01-СЕН-09','DD-MON-RR'),1,5);
Insert into DEKANAT.STUDENTS (ID_STUDENT,LAST_NAME,FIRST_NAME,THIRD_NAME,BIRTHDAY,EXPIRY_STATUS,ENTER_DATE,ID_STATUS,ID_GROUP) values (16,'Беляев','Илья','---',to_date('01-ЯНВ-92','DD-MON-RR'),to_date('25-ДЕК-11','DD-MON-RR'),to_date('01-СЕН-09','DD-MON-RR'),1,5);
Insert into DEKANAT.STUDENTS (ID_STUDENT,LAST_NAME,FIRST_NAME,THIRD_NAME,BIRTHDAY,EXPIRY_STATUS,ENTER_DATE,ID_STATUS,ID_GROUP) values (24,'Владимиров','Сергей','Викторович',to_date('01-ЯНВ-87','DD-MON-RR'),to_date('30-ИЮН-11','DD-MON-RR'),to_date('01-СЕН-07','DD-MON-RR'),4,5);
