--------------------------------------------------------
--  Ref Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "DEKANAT"."STUDENTS" ADD CONSTRAINT "GROUPS2STUDENTS" FOREIGN KEY ("ID_GROUP")
	  REFERENCES "DEKANAT"."GROUPS" ("ID_GROUP") ON DELETE SET NULL ENABLE;
  ALTER TABLE "DEKANAT"."STUDENTS" ADD CONSTRAINT "STATUSES2STUDENTS" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "DEKANAT"."STATUSES" ("ID_STATUS") ON DELETE SET NULL ENABLE;
