REM INSERTING into DEKANAT.TEACHERS2DISCIPLINES
Insert into DEKANAT.TEACHERS2DISCIPLINES (TEACHERS_ID_TEACHER,DISCIPLINES_ID_DISCIPLINE) values (1,5);
Insert into DEKANAT.TEACHERS2DISCIPLINES (TEACHERS_ID_TEACHER,DISCIPLINES_ID_DISCIPLINE) values (1,6);
Insert into DEKANAT.TEACHERS2DISCIPLINES (TEACHERS_ID_TEACHER,DISCIPLINES_ID_DISCIPLINE) values (2,1);
Insert into DEKANAT.TEACHERS2DISCIPLINES (TEACHERS_ID_TEACHER,DISCIPLINES_ID_DISCIPLINE) values (2,4);
Insert into DEKANAT.TEACHERS2DISCIPLINES (TEACHERS_ID_TEACHER,DISCIPLINES_ID_DISCIPLINE) values (21,7);
