--------------------------------------------------------
--  DDL for View VIEW_MARKS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DEKANAT"."VIEW_MARKS" ("COURSE", "ID_GROUP", "GROUPNAME", "FULLNAME", "VALUE_MARK", "DATE_MARK", "DISCNAME") AS 
  SELECT        G.COURSE, G.ID_GROUP, GET_GROUPNAME(G.NAME_GROUP, G.COURSE, G.SUBGROUP) AS GROUPNAME, GET_FULLNAME(S.LAST_NAME, S.FIRST_NAME, S.THIRD_NAME) 
                         AS FULLNAME, M.VALUE_MARK, M.DATE_MARK, GET_DISCNAME(D.ID_DISCNAME) AS DISCNAME
FROM            MARKS M, STUDENTS S, "GROUPS" G, DISCIPLINES D
WHERE        M.ID_STUDENT = S.ID_STUDENT AND S.ID_GROUP = G.ID_GROUP AND M.ID_DISCIPLINE = D.ID_DISCIPLINE AND (S.ID_STATUS = 1)
ORDER BY GROUPNAME, FULLNAME;
